version: '3'
services:

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: app
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/app/php-settings.ini:/usr/local/etc/php/conf.d/php-settings.ini

    working_dir: /var/www
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  #MySQL Service
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  redis_data:

